

let Product_dataArr = [
  {
    discount: "-10%",
    name: "YishensuGroceries",
    image_url: "https://www.kindmeal.my/YishensuGroceries/deal-720.htm",
    dish: "Yishensu Groceries @ Ipoh",
    dish_url: "https://www.kindmeal.my/YishensuGroceries/deal-720.htm",
    location: "Yishensu Groceries Ipoh— Ipoh, Perak",
    location_url: "https://www.kindmeal.my/YishensuGroceries",
    about:
      "Yishensu Groceries, Ipoh offers you a wide range of healthy, nutritious and tasty vegetarian products! We develop our own exclus",
    free_coupon: "Get FREE Coupon",
    free_coupon_url: "https://www.kindmeal.my/YishensuGroceries/deal-720.htm",
    ratings: "https://www.kindmeal.my/images/icon_star_grey.png",
    eggfree: "https://www.kindmeal.my/images/icon_egg.png",
    dairyfree: "https://www.kindmeal.my/images/icon_milk_disabled.png",
    beerfree: "https://www.kindmeal.my/images/icon_alcohol_disabled.png",
    kind_meal: "KindMeal Discount",
    kindmeal_discount: "10% Off",
    expires_in: "Expires In",
    expires: "5 Days",
  },
  {
    discount: "-10%",
    name: "Vegelab",
    image_url: "https://www.kindmeal.my/Vegelab/deal-649.htm",
    dish: "Fusion Western Delicacies",
    dish_url: "https://www.kindmeal.my/Vegelab/deal-649.htm",
    location: "Vegelab— Cheras, Kuala Lumpur",
    location_url: "https://www.kindmeal.my/Vegelab",
    about:
      "Experience our delectable selection of fusion Western cuisine, crafted with heart to promote a healthy and compassionate eating li..",
    free_coupon: "Get FREE Coupon",
    free_coupon_url: "https://www.kindmeal.my/Vegelab/deal-649.htm",
    ratings: "https://www.kindmeal.my/images/icon_star.png",
    eggfree: "https://www.kindmeal.my/images/icon_egg.png",
    dairyfree: "https://www.kindmeal.my/images/icon_milk.png",
    beerfree: "https://www.kindmeal.my/images/icon_alcohol_disabled.png",
    Kind_meal: "KindMeal Discount",
    Kindmeal_discount: "10% Off",
    expires_in: "Expires In",
    expires: "6 Days",
  },
  {
    discount: "-10%",
    name: "Hijau",
    image_url: "https://www.kindmeal.my/Hijau/deal-712.htm",
    dish: "Malaysian Vegan Experience",
    dish_url: "https://www.kindmeal.my/Hijau/deal-712.htm",
    location: "Hijau",
    location_url: "https://www.kindmeal.my/Hijau",
    about:
      "Indulge in Malay-Indo fusion cuisine, a plant-based comfort food and healthy pleasure! Hijau is your go-to, where you can embrac..",
    free_coupon: "Get FREE Coupon",
    free_coupon_url: "https://www.kindmeal.my/Hijau/deal-712.htm",
    ratings: "https://www.kindmeal.my/images/icon_star.png",
    eggfree: "https://www.kindmeal.my/images/icon_egg_disabled.png",
    dairyfree: "https://www.kindmeal.my/images/icon_milk_disabled.png",
    beerfree: "https://www.kindmeal.my/images/icon_alcohol_disabled.png",
    Kind_meal: "KindMeal Discount",
    Kindmeal_discount: "10% Off",
    expires_in: "Expires In",
    expires: "8 Days",
  },
  {
    discount: "-20%",
    name: "JamaicaBlue",
    image_url: "https://www.kindmeal.my/JamaicaBlue/deal-551.htm",
    dish: "Fine Coffees & Fabulous Food",
    dish_url: "https://www.kindmeal.my/JamaicaBlue/deal-551.htm",
    location: "Jamaica Blue— Shah Alam & 1 Branch",
    location_url: "https://www.kindmeal.my/JamaicaBlue",
    about:
      "Serving classic dishes with a contemporary twist, using the freshest and seasonal ingredients. Select from any of our meat-free i..",
    free_coupon: "Get FREE Coupon",
    free_coupon_url: "https://www.kindmeal.my/JamaicaBlue/deal-551.htm",
    ratings: "https://www.kindmeal.my/images/icon_star.png",
    eggfree: "https://www.kindmeal.my/images/icon_egg.png",
    dairyfree: "https://www.kindmeal.my/images/icon_milk.png",
    beerfree: "https://www.kindmeal.my/images/icon_alcohol_disabled.png",
    Kind_meal: "KindMeal Discount",
    Kindmeal_discount: "20% Off",
    expires_in: "Expires In",
    expires: "12 Days",
  },
  {
    discount: "-20%",
    name: "DiningBowl",
    image_url: "https://www.kindmeal.my/DiningBowl/deal-383.htm",
    dish: "Dining Bowl Asian Delicacies",
    dish_url: "https://www.kindmeal.my/DiningBowl/deal-383.htm",
    location: "Dining Bowl— Kuala Lumpur, Wilayah Persekutuan",
    location_url: "https://www.kindmeal.my/DiningBowl",
    about:
      "Dine in this authentic cozy Chinese environment with any items from the menu, made with fresh and quality ingredients, in an envir..",
    free_coupon: "Get FREE Coupon",
    free_coupon_url: "https://www.kindmeal.my/DiningBowl/deal-383.htm",
    ratings: "https://www.kindmeal.my/images/icon_star.png",
    eggfree: "https://www.kindmeal.my/images/icon_egg.png",
    dairyfree: "https://www.kindmeal.my/images/icon_milk.png",
    beerfree: "https://www.kindmeal.my/images/icon_alcohol_disabled.png",
    Kind_meal: "KindMeal Discount",
    kindmeal_discount: "20% Off",
    expires_in: "Expires In",
    expires: "10 Days",
  },
  {
    discount: "-20%",
    name: "Cameleon",
    image_url: "https://www.kindmeal.my/Cameleon/deal-610.htm",
    dish: "Authentic Asian Experience",
    dish_url: "https://www.kindmeal.my/Cameleon/deal-610.htm",
    location:
      "Cameleon Vegetarian Restaurant — Kuala Lumpur, Wilayah Persekutuan",
    about:
      "Indulge yourself in healthy, authentic Asian cuisines within a traditional dinning environment. Enjoy any items from our ala cart..",
    free_caupon: "Get FREE Coupon",
    free_coupon_url: "https://www.kindmeal.my/Cameleon/deal-610.htm",
    ratings: "https://www.kindmeal.my/images/icon_star.png",
    eggfree: "https://www.kindmeal.my/images/icon_egg_disabled.png",
    dairyfree: "https://www.kindmeal.my/images/icon_milk.png",
    beerfree: "https://www.kindmeal.my/images/icon_alcohol_disabled.png",
    Kind_meal: "KindMeal Discount",
    kindmeal_discount: "20% Off",
    expires_in: "Expires In",
    expires: "13 Days",
  },
  {
    discount: "-20%",
    name: "BlackCatCafe",
    image_url: "https://www.kindmeal.my/BlackCatCafe/deal-457.htm",
    dish: "Flavours Around the World",
    dish_url: "https://www.kindmeal.my/BlackCatCafe/deal-457.htm",
    location: "The Black Cat Cafe — Kuala Lumpur, Wilayah Persekutuan",
    about:
      "Western and Asian cuisine, all prepared in our humble kitchen with utmost passion and love. On Weekdays, select ANY items from ..",
    free_caupon: "Get FREE Coupon",
    free_coupon_url: "https://www.kindmeal.my/BlackCatCafe/deal-457.htm",
    ratings: "https://www.kindmeal.my/images/icon_star.png",
    eggfree: "https://www.kindmeal.my/images/icon_egg.png",
    dairyfree: "https://www.kindmeal.my/images/icon_milk.png",
    beerfree: "https://www.kindmeal.my/images/icon_alcohol_disabled.png",
    Kind_meal: "KindMeal Discount",
    kindmeal_discount: "20% Off",
    expires_in: "Expires In",
    expires: "12 Days",
  },
  {
    discount: "-20%",
    name: "SsihatKafe",
    image_url: "https://www.kindmeal.my/SsihatKafe/deal-626.htm",
    dish: "Melakan Indian Fusion Cuisine",
    dish_url: "https://www.kindmeal.my/SsihatKafe/deal-626.htm",
    location: "Ssihat Kafe — Melaka",
    about:
      "Ignite your taste buds with indian spices and flavours at Melaka's only Indian fully Vegetarian Cafe. We humbly welcome you and y..",
    free_caupon: "Get FREE Coupon",
    free_coupon_url: "https://www.kindmeal.my/SsihatKafe/deal-626.htm",
    ratings: "https://www.kindmeal.my/images/icon_star_grey.png",
    eggfree: "https://www.kindmeal.my/images/icon_egg_disabled.png",
    dairyfree: "https://www.kindmeal.my/images/icon_milk.png",
    beerfree: "https://www.kindmeal.my/images/icon_alcohol_disabled.png",
    Kind_meal: "KindMeal Discount",
    kindmeal_discount: "20% Off",
    expiry: "5 Days",
  },
  {
    discount: "-20%",
    name: "JuveWellness",
    image_url: "https://www.kindmeal.my/JuveWellness/deal-403.htm",
    dish: "Wellness Meal + 10% Off Organic Products",
    dish_url: "https://www.kindmeal.my/JuveWellness/deal-403.htm",
    location: "Juve Wellness Puchong — Puchong, Selangor",
    about:
      "Select from Ala Carte meal items from the menu, served with a cup of Wellness Tea! Featured food menu items include: Juve Four Se..\nGet FREE Coupon\n(4)",
    free_caupon: "Get FREE Coupon",
    free_coupon_url: "https://www.kindmeal.my/JuveWellness/deal-403.htm",
    ratings: "https://www.kindmeal.my/images/icon_star.png",
    eggfree: "https://www.kindmeal.my/images/icon_egg_disabled.png",
    dairyfree: "https://www.kindmeal.my/images/icon_milk_disabled.png",
    beerfree: "https://www.kindmeal.my/images/icon_alcohol_disabled.png",
    Kind_meal: "KindMeal Discount",
    kindmeal_discount: "20% Off",
    expiry: "5 Days",
  },
  {
    discount: "-20%",
    name: "Croutons",
    image_url: "https://www.kindmeal.my/Croutons/deal-529.htm",
    dish: "Scrumptious Croutons",
    dish_url: "https://www.kindmeal.my/Croutons/deal-529.htm",
    location: "Croutons Cafe — Seri Kembangan, Selangor",
    about:
      "Croutons brings you a sumptuous variety of international cuisines. Indulge in any of the meat-free items from our menu below: • ..",
    free_caupon: "Get FREE Coupon",
    free_coupon_url: "https://www.kindmeal.my/Croutons/deal-529.htm",
    ratings: "https://www.kindmeal.my/images/icon_star.png",
    eggfree: "https://www.kindmeal.my/images/icon_egg.png",
    dairyfree: "https://www.kindmeal.my/images/icon_milk.png",
    beerfree: "https://www.kindmeal.my/images/icon_alcohol.png",
    Kind_meal: "KindMeal Discount",
    kindmeal_discount: "20% Off",
    expiry: "13 Days",
  },
];
